
static ZONE1970_PRIMARY: &[&str] = &[
    "Africa/Abidjan",
    "Africa/Algiers",
    "Africa/Bissau",
    "Africa/Cairo",
    "Africa/Casablanca",
    "Africa/Ceuta",
    "Africa/El_Aaiun",
    "Africa/Johannesburg",
    "Africa/Juba",
    "Africa/Khartoum",
    "Africa/Lagos",
    "Africa/Maputo",
    "Africa/Monrovia",
    "Africa/Nairobi",
    "Africa/Ndjamena",
    "Africa/Sao_Tome",
    "Africa/Tripoli",
    "Africa/Tunis",
    "Africa/Windhoek",
    "America/Adak",
    "America/Anchorage",
    "America/Araguaina",
    "America/Argentina/Buenos_Aires",
    "America/Argentina/Catamarca",
    "America/Argentina/Cordoba",
    "America/Argentina/Jujuy",
    "America/Argentina/La_Rioja",
    "America/Argentina/Mendoza",
    "America/Argentina/Rio_Gallegos",
    "America/Argentina/Salta",
    "America/Argentina/San_Juan",
    "America/Argentina/San_Luis",
    "America/Argentina/Tucuman",
    "America/Argentina/Ushuaia",
    "America/Asuncion",
    "America/Bahia",
    "America/Bahia_Banderas",
    "America/Barbados",
    "America/Belem",
    "America/Belize",
    "America/Boa_Vista",
    "America/Bogota",
    "America/Boise",
    "America/Cambridge_Bay",
    "America/Campo_Grande",
    "America/Cancun",
    "America/Caracas",
    "America/Cayenne",
    "America/Chicago",
    "America/Chihuahua",
    "America/Ciudad_Juarez",
    "America/Costa_Rica",
    "America/Coyhaique",
    "America/Cuiaba",
    "America/Danmarkshavn",
    "America/Dawson",
    "America/Dawson_Creek",
    "America/Denver",
    "America/Detroit",
    "America/Edmonton",
    "America/Eirunepe",
    "America/El_Salvador",
    "America/Fort_Nelson",
    "America/Fortaleza",
    "America/Glace_Bay",
    "America/Goose_Bay",
    "America/Grand_Turk",
    "America/Guatemala",
    "America/Guayaquil",
    "America/Guyana",
    "America/Halifax",
    "America/Havana",
    "America/Hermosillo",
    "America/Indiana/Indianapolis",
    "America/Indiana/Knox",
    "America/Indiana/Marengo",
    "America/Indiana/Petersburg",
    "America/Indiana/Tell_City",
    "America/Indiana/Vevay",
    "America/Indiana/Vincennes",
    "America/Indiana/Winamac",
    "America/Inuvik",
    "America/Iqaluit",
    "America/Jamaica",
    "America/Juneau",
    "America/Kentucky/Louisville",
    "America/Kentucky/Monticello",
    "America/La_Paz",
    "America/Lima",
    "America/Los_Angeles",
    "America/Maceio",
    "America/Managua",
    "America/Manaus",
    "America/Martinique",
    "America/Matamoros",
    "America/Mazatlan",
    "America/Menominee",
    "America/Merida",
    "America/Metlakatla",
    "America/Mexico_City",
    "America/Miquelon",
    "America/Moncton",
    "America/Monterrey",
    "America/Montevideo",
    "America/New_York",
    "America/Nome",
    "America/Noronha",
    "America/North_Dakota/Beulah",
    "America/North_Dakota/Center",
    "America/North_Dakota/New_Salem",
    "America/Nuuk",
    "America/Ojinaga",
    "America/Panama",
    "America/Paramaribo",
    "America/Phoenix",
    "America/Port-au-Prince",
    "America/Porto_Velho",
    "America/Puerto_Rico",
    "America/Punta_Arenas",
    "America/Rankin_Inlet",
    "America/Recife",
    "America/Regina",
    "America/Resolute",
    "America/Rio_Branco",
    "America/Santarem",
    "America/Santiago",
    "America/Santo_Domingo",
    "America/Sao_Paulo",
    "America/Scoresbysund",
    "America/Sitka",
    "America/St_Johns",
    "America/Swift_Current",
    "America/Tegucigalpa",
    "America/Thule",
    "America/Tijuana",
    "America/Toronto",
    "America/Vancouver",
    "America/Whitehorse",
    "America/Winnipeg",
    "America/Yakutat",
    "Antarctica/Casey",
    "Antarctica/Davis",
    "Antarctica/Macquarie",
    "Antarctica/Mawson",
    "Antarctica/Palmer",
    "Antarctica/Rothera",
    "Antarctica/Troll",
    "Antarctica/Vostok",
    "Asia/Almaty",
    "Asia/Amman",
    "Asia/Anadyr",
    "Asia/Aqtau",
    "Asia/Aqtobe",
    "Asia/Ashgabat",
    "Asia/Atyrau",
    "Asia/Baghdad",
    "Asia/Baku",
    "Asia/Bangkok",
    "Asia/Barnaul",
    "Asia/Beirut",
    "Asia/Bishkek",
    "Asia/Chita",
    "Asia/Colombo",
    "Asia/Damascus",
    "Asia/Dhaka",
    "Asia/Dili",
    "Asia/Dubai",
    "Asia/Dushanbe",
    "Asia/Famagusta",
    "Asia/Gaza",
    "Asia/Hebron",
    "Asia/Ho_Chi_Minh",
    "Asia/Hong_Kong",
    "Asia/Hovd",
    "Asia/Irkutsk",
    "Asia/Jakarta",
    "Asia/Jayapura",
    "Asia/Jerusalem",
    "Asia/Kabul",
    "Asia/Kamchatka",
    "Asia/Karachi",
    "Asia/Kathmandu",
    "Asia/Khandyga",
    "Asia/Kolkata",
    "Asia/Krasnoyarsk",
    "Asia/Kuching",
    "Asia/Macau",
    "Asia/Magadan",
    "Asia/Makassar",
    "Asia/Manila",
    "Asia/Nicosia",
    "Asia/Novokuznetsk",
    "Asia/Novosibirsk",
    "Asia/Omsk",
    "Asia/Oral",
    "Asia/Pontianak",
    "Asia/Pyongyang",
    "Asia/Qatar",
    "Asia/Qostanay",
    "Asia/Qyzylorda",
    "Asia/Riyadh",
    "Asia/Sakhalin",
    "Asia/Samarkand",
    "Asia/Seoul",
    "Asia/Shanghai",
    "Asia/Singapore",
    "Asia/Srednekolymsk",
    "Asia/Taipei",
    "Asia/Tashkent",
    "Asia/Tbilisi",
    "Asia/Tehran",
    "Asia/Thimphu",
    "Asia/Tokyo",
    "Asia/Tomsk",
    "Asia/Ulaanbaatar",
    "Asia/Urumqi",
    "Asia/Ust-Nera",
    "Asia/Vladivostok",
    "Asia/Yakutsk",
    "Asia/Yangon",
    "Asia/Yekaterinburg",
    "Asia/Yerevan",
    "Atlantic/Azores",
    "Atlantic/Bermuda",
    "Atlantic/Canary",
    "Atlantic/Cape_Verde",
    "Atlantic/Faroe",
    "Atlantic/Madeira",
    "Atlantic/South_Georgia",
    "Atlantic/Stanley",
    "Australia/Adelaide",
    "Australia/Brisbane",
    "Australia/Broken_Hill",
    "Australia/Darwin",
    "Australia/Eucla",
    "Australia/Hobart",
    "Australia/Lindeman",
    "Australia/Lord_Howe",
    "Australia/Melbourne",
    "Australia/Perth",
    "Australia/Sydney",
    "Europe/Andorra",
    "Europe/Astrakhan",
    "Europe/Athens",
    "Europe/Belgrade",
    "Europe/Berlin",
    "Europe/Brussels",
    "Europe/Bucharest",
    "Europe/Budapest",
    "Europe/Chisinau",
    "Europe/Dublin",
    "Europe/Gibraltar",
    "Europe/Helsinki",
    "Europe/Istanbul",
    "Europe/Kaliningrad",
    "Europe/Kirov",
    "Europe/Kyiv",
    "Europe/Lisbon",
    "Europe/London",
    "Europe/Madrid",
    "Europe/Malta",
    "Europe/Minsk",
    "Europe/Moscow",
    "Europe/Paris",
    "Europe/Prague",
    "Europe/Riga",
    "Europe/Rome",
    "Europe/Samara",
    "Europe/Saratov",
    "Europe/Simferopol",
    "Europe/Sofia",
    "Europe/Tallinn",
    "Europe/Tirane",
    "Europe/Ulyanovsk",
    "Europe/Vienna",
    "Europe/Vilnius",
    "Europe/Volgograd",
    "Europe/Warsaw",
    "Europe/Zurich",
    "Indian/Chagos",
    "Indian/Maldives",
    "Indian/Mauritius",
    "Pacific/Apia",
    "Pacific/Auckland",
    "Pacific/Bougainville",
    "Pacific/Chatham",
    "Pacific/Easter",
    "Pacific/Efate",
    "Pacific/Fakaofo",
    "Pacific/Fiji",
    "Pacific/Galapagos",
    "Pacific/Gambier",
    "Pacific/Guadalcanal",
    "Pacific/Guam",
    "Pacific/Honolulu",
    "Pacific/Kanton",
    "Pacific/Kiritimati",
    "Pacific/Kosrae",
    "Pacific/Kwajalein",
    "Pacific/Marquesas",
    "Pacific/Nauru",
    "Pacific/Niue",
    "Pacific/Norfolk",
    "Pacific/Noumea",
    "Pacific/Pago_Pago",
    "Pacific/Palau",
    "Pacific/Pitcairn",
    "Pacific/Port_Moresby",
    "Pacific/Rarotonga",
    "Pacific/Tahiti",
    "Pacific/Tarawa",
    "Pacific/Tongatapu",
];

static BACKWARD_LINKS: &[(&str, &str)] = &[
    ("Africa/Abidjan", "Africa/Accra"),
    ("Africa/Nairobi", "Africa/Addis_Ababa"),
    ("Africa/Nairobi", "Africa/Asmara"),
    ("Africa/Nairobi", "Africa/Asmera"),
    ("Africa/Abidjan", "Africa/Bamako"),
    ("Africa/Lagos", "Africa/Bangui"),
    ("Africa/Abidjan", "Africa/Banjul"),
    ("Africa/Maputo", "Africa/Blantyre"),
    ("Africa/Lagos", "Africa/Brazzaville"),
    ("Africa/Maputo", "Africa/Bujumbura"),
    ("Africa/Abidjan", "Africa/Conakry"),
    ("Africa/Abidjan", "Africa/Dakar"),
    ("Africa/Nairobi", "Africa/Dar_es_Salaam"),
    ("Africa/Nairobi", "Africa/Djibouti"),
    ("Africa/Lagos", "Africa/Douala"),
    ("Africa/Abidjan", "Africa/Freetown"),
    ("Africa/Maputo", "Africa/Gaborone"),
    ("Africa/Maputo", "Africa/Harare"),
    ("Africa/Nairobi", "Africa/Kampala"),
    ("Africa/Maputo", "Africa/Kigali"),
    ("Africa/Lagos", "Africa/Kinshasa"),
    ("Africa/Lagos", "Africa/Libreville"),
    ("Africa/Abidjan", "Africa/Lome"),
    ("Africa/Lagos", "Africa/Luanda"),
    ("Africa/Maputo", "Africa/Lubumbashi"),
    ("Africa/Maputo", "Africa/Lusaka"),
    ("Africa/Lagos", "Africa/Malabo"),
    ("Africa/Johannesburg", "Africa/Maseru"),
    ("Africa/Johannesburg", "Africa/Mbabane"),
    ("Africa/Nairobi", "Africa/Mogadishu"),
    ("Africa/Lagos", "Africa/Niamey"),
    ("Africa/Abidjan", "Africa/Nouakchott"),
    ("Africa/Abidjan", "Africa/Ouagadougou"),
    ("Africa/Lagos", "Africa/Porto-Novo"),
    ("Africa/Abidjan", "Africa/Timbuktu"),
    ("America/Puerto_Rico", "America/Anguilla"),
    ("America/Puerto_Rico", "America/Antigua"),
    (
        "America/Argentina/Catamarca",
        "America/Argentina/ComodRivadavia",
    ),
    ("America/Puerto_Rico", "America/Aruba"),
    ("America/Panama", "America/Atikokan"),
    ("America/Adak", "America/Atka"),
    ("America/Puerto_Rico", "America/Blanc-Sablon"),
    ("America/Argentina/Buenos_Aires", "America/Buenos_Aires"),
    ("America/Argentina/Catamarca", "America/Catamarca"),
    ("America/Panama", "America/Cayman"),
    ("America/Panama", "America/Coral_Harbour"),
    ("America/Argentina/Cordoba", "America/Cordoba"),
    ("America/Phoenix", "America/Creston"),
    ("America/Puerto_Rico", "America/Curacao"),
    ("America/Puerto_Rico", "America/Dominica"),
    ("America/Tijuana", "America/Ensenada"),
    ("America/Indiana/Indianapolis", "America/Fort_Wayne"),
    ("America/Nuuk", "America/Godthab"),
    ("America/Puerto_Rico", "America/Grenada"),
    ("America/Puerto_Rico", "America/Guadeloupe"),
    ("America/Indiana/Indianapolis", "America/Indianapolis"),
    ("America/Argentina/Jujuy", "America/Jujuy"),
    ("America/Indiana/Knox", "America/Knox_IN"),
    ("America/Puerto_Rico", "America/Kralendijk"),
    ("America/Kentucky/Louisville", "America/Louisville"),
    ("America/Puerto_Rico", "America/Lower_Princes"),
    ("America/Puerto_Rico", "America/Marigot"),
    ("America/Argentina/Mendoza", "America/Mendoza"),
    ("America/Toronto", "America/Montreal"),
    ("America/Puerto_Rico", "America/Montserrat"),
    ("America/Toronto", "America/Nassau"),
    ("America/Toronto", "America/Nipigon"),
    ("America/Iqaluit", "America/Pangnirtung"),
    ("America/Puerto_Rico", "America/Port_of_Spain"),
    ("America/Rio_Branco", "America/Porto_Acre"),
    ("America/Winnipeg", "America/Rainy_River"),
    ("America/Argentina/Cordoba", "America/Rosario"),
    ("America/Tijuana", "America/Santa_Isabel"),
    ("America/Denver", "America/Shiprock"),
    ("America/Puerto_Rico", "America/St_Barthelemy"),
    ("America/Puerto_Rico", "America/St_Kitts"),
    ("America/Puerto_Rico", "America/St_Lucia"),
    ("America/Puerto_Rico", "America/St_Thomas"),
    ("America/Puerto_Rico", "America/St_Vincent"),
    ("America/Toronto", "America/Thunder_Bay"),
    ("America/Puerto_Rico", "America/Tortola"),
    ("America/Puerto_Rico", "America/Virgin"),
    ("America/Edmonton", "America/Yellowknife"),
    ("Pacific/Port_Moresby", "Antarctica/DumontDUrville"),
    ("Pacific/Auckland", "Antarctica/McMurdo"),
    ("Pacific/Auckland", "Antarctica/South_Pole"),
    ("Asia/Riyadh", "Antarctica/Syowa"),
    ("Europe/Berlin", "Arctic/Longyearbyen"),
    ("Asia/Riyadh", "Asia/Aden"),
    ("Asia/Ashgabat", "Asia/Ashkhabad"),
    ("Asia/Qatar", "Asia/Bahrain"),
    ("Asia/Kuching", "Asia/Brunei"),
    ("Asia/Kolkata", "Asia/Calcutta"),
    ("Asia/Ulaanbaatar", "Asia/Choibalsan"),
    ("Asia/Shanghai", "Asia/Chongqing"),
    ("Asia/Shanghai", "Asia/Chungking"),
    ("Asia/Dhaka", "Asia/Dacca"),
    ("Asia/Shanghai", "Asia/Harbin"),
    ("Europe/Istanbul", "Asia/Istanbul"),
    ("Asia/Urumqi", "Asia/Kashgar"),
    ("Asia/Kathmandu", "Asia/Katmandu"),
    ("Asia/Singapore", "Asia/Kuala_Lumpur"),
    ("Asia/Riyadh", "Asia/Kuwait"),
    ("Asia/Macau", "Asia/Macao"),
    ("Asia/Dubai", "Asia/Muscat"),
    ("Asia/Bangkok", "Asia/Phnom_Penh"),
    ("Asia/Yangon", "Asia/Rangoon"),
    ("Asia/Ho_Chi_Minh", "Asia/Saigon"),
    ("Asia/Jerusalem", "Asia/Tel_Aviv"),
    ("Asia/Thimphu", "Asia/Thimbu"),
    ("Asia/Makassar", "Asia/Ujung_Pandang"),
    ("Asia/Ulaanbaatar", "Asia/Ulan_Bator"),
    ("Asia/Bangkok", "Asia/Vientiane"),
    ("Atlantic/Faroe", "Atlantic/Faeroe"),
    ("Europe/Berlin", "Atlantic/Jan_Mayen"),
    ("Africa/Abidjan", "Atlantic/Reykjavik"),
    ("Africa/Abidjan", "Atlantic/St_Helena"),
    ("Australia/Sydney", "Australia/ACT"),
    ("Australia/Sydney", "Australia/Canberra"),
    ("Australia/Hobart", "Australia/Currie"),
    ("Australia/Lord_Howe", "Australia/LHI"),
    ("Australia/Sydney", "Australia/NSW"),
    ("Australia/Darwin", "Australia/North"),
    ("Australia/Brisbane", "Australia/Queensland"),
    ("Australia/Adelaide", "Australia/South"),
    ("Australia/Hobart", "Australia/Tasmania"),
    ("Australia/Melbourne", "Australia/Victoria"),
    ("Australia/Perth", "Australia/West"),
    ("Australia/Broken_Hill", "Australia/Yancowinna"),
    ("America/Rio_Branco", "Brazil/Acre"),
    ("America/Noronha", "Brazil/DeNoronha"),
    ("America/Sao_Paulo", "Brazil/East"),
    ("America/Manaus", "Brazil/West"),
    ("Europe/Brussels", "CET"),
    ("America/Chicago", "CST6CDT"),
    ("America/Halifax", "Canada/Atlantic"),
    ("America/Winnipeg", "Canada/Central"),
    ("America/Toronto", "Canada/Eastern"),
    ("America/Edmonton", "Canada/Mountain"),
    ("America/St_Johns", "Canada/Newfoundland"),
    ("America/Vancouver", "Canada/Pacific"),
    ("America/Regina", "Canada/Saskatchewan"),
    ("America/Whitehorse", "Canada/Yukon"),
    ("America/Santiago", "Chile/Continental"),
    ("Pacific/Easter", "Chile/EasterIsland"),
    ("America/Havana", "Cuba"),
    ("Europe/Athens", "EET"),
    ("America/Panama", "EST"),
    ("America/New_York", "EST5EDT"),
    ("Africa/Cairo", "Egypt"),
    ("Europe/Dublin", "Eire"),
    ("Etc/GMT", "Etc/GMT+0"),
    ("Etc/GMT", "Etc/GMT-0"),
    ("Etc/GMT", "Etc/GMT0"),
    ("Etc/GMT", "Etc/Greenwich"),
    ("Etc/UTC", "Etc/UCT"),
    ("Etc/UTC", "Etc/Universal"),
    ("Etc/UTC", "Etc/Zulu"),
    ("Europe/Brussels", "Europe/Amsterdam"),
    ("Europe/London", "Europe/Belfast"),
    ("Europe/Prague", "Europe/Bratislava"),
    ("Europe/Zurich", "Europe/Busingen"),
    ("Europe/Berlin", "Europe/Copenhagen"),
    ("Europe/London", "Europe/Guernsey"),
    ("Europe/London", "Europe/Isle_of_Man"),
    ("Europe/London", "Europe/Jersey"),
    ("Europe/Kyiv", "Europe/Kiev"),
    ("Europe/Belgrade", "Europe/Ljubljana"),
    ("Europe/Brussels", "Europe/Luxembourg"),
    ("Europe/Helsinki", "Europe/Mariehamn"),
    ("Europe/Paris", "Europe/Monaco"),
    ("Asia/Nicosia", "Europe/Nicosia"),
    ("Europe/Berlin", "Europe/Oslo"),
    ("Europe/Belgrade", "Europe/Podgorica"),
    ("Europe/Rome", "Europe/San_Marino"),
    ("Europe/Belgrade", "Europe/Sarajevo"),
    ("Europe/Belgrade", "Europe/Skopje"),
    ("Europe/Berlin", "Europe/Stockholm"),
    ("Europe/Chisinau", "Europe/Tiraspol"),
    ("Europe/Kyiv", "Europe/Uzhgorod"),
    ("Europe/Zurich", "Europe/Vaduz"),
    ("Europe/Rome", "Europe/Vatican"),
    ("Europe/Belgrade", "Europe/Zagreb"),
    ("Europe/Kyiv", "Europe/Zaporozhye"),
    ("Europe/London", "GB"),
    ("Europe/London", "GB-Eire"),
    ("Etc/GMT", "GMT+0"),
    ("Etc/GMT", "GMT-0"),
    ("Etc/GMT", "GMT0"),
    ("Etc/GMT", "Greenwich"),
    ("Pacific/Honolulu", "HST"),
    ("Asia/Hong_Kong", "Hongkong"),
    ("Africa/Abidjan", "Iceland"),
    ("Africa/Nairobi", "Indian/Antananarivo"),
    ("Asia/Bangkok", "Indian/Christmas"),
    ("Asia/Yangon", "Indian/Cocos"),
    ("Africa/Nairobi", "Indian/Comoro"),
    ("Indian/Maldives", "Indian/Kerguelen"),
    ("Asia/Dubai", "Indian/Mahe"),
    ("Africa/Nairobi", "Indian/Mayotte"),
    ("Asia/Dubai", "Indian/Reunion"),
    ("Asia/Tehran", "Iran"),
    ("Asia/Jerusalem", "Israel"),
    ("America/Jamaica", "Jamaica"),
    ("Asia/Tokyo", "Japan"),
    ("Pacific/Kwajalein", "Kwajalein"),
    ("Africa/Tripoli", "Libya"),
    ("Europe/Brussels", "MET"),
    ("America/Phoenix", "MST"),
    ("America/Denver", "MST7MDT"),
    ("America/Tijuana", "Mexico/BajaNorte"),
    ("America/Mazatlan", "Mexico/BajaSur"),
    ("America/Mexico_City", "Mexico/General"),
    ("Pacific/Auckland", "NZ"),
    ("Pacific/Chatham", "NZ-CHAT"),
    ("America/Denver", "Navajo"),
    ("Asia/Shanghai", "PRC"),
    ("America/Los_Angeles", "PST8PDT"),
    ("Pacific/Port_Moresby", "Pacific/Chuuk"),
    ("Pacific/Kanton", "Pacific/Enderbury"),
    ("Pacific/Tarawa", "Pacific/Funafuti"),
    ("Pacific/Honolulu", "Pacific/Johnston"),
    ("Pacific/Tarawa", "Pacific/Majuro"),
    ("Pacific/Pago_Pago", "Pacific/Midway"),
    ("Pacific/Guadalcanal", "Pacific/Pohnpei"),
    ("Pacific/Guadalcanal", "Pacific/Ponape"),
    ("Pacific/Guam", "Pacific/Saipan"),
    ("Pacific/Pago_Pago", "Pacific/Samoa"),
    ("Pacific/Port_Moresby", "Pacific/Truk"),
    ("Pacific/Tarawa", "Pacific/Wake"),
    ("Pacific/Tarawa", "Pacific/Wallis"),
    ("Pacific/Port_Moresby", "Pacific/Yap"),
    ("Europe/Warsaw", "Poland"),
    ("Europe/Lisbon", "Portugal"),
    ("Asia/Taipei", "ROC"),
    ("Asia/Seoul", "ROK"),
    ("Asia/Singapore", "Singapore"),
    ("Europe/Istanbul", "Turkey"),
    ("Etc/UTC", "UCT"),
    ("America/Anchorage", "US/Alaska"),
    ("America/Adak", "US/Aleutian"),
    ("America/Phoenix", "US/Arizona"),
    ("America/Chicago", "US/Central"),
    ("America/Indiana/Indianapolis", "US/East-Indiana"),
    ("America/New_York", "US/Eastern"),
    ("Pacific/Honolulu", "US/Hawaii"),
    ("America/Indiana/Knox", "US/Indiana-Starke"),
    ("America/Detroit", "US/Michigan"),
    ("America/Denver", "US/Mountain"),
    ("America/Los_Angeles", "US/Pacific"),
    ("Pacific/Pago_Pago", "US/Samoa"),
    ("Etc/UTC", "UTC"),
    ("Etc/UTC", "Universal"),
    ("Europe/Moscow", "W-SU"),
    ("Europe/Lisbon", "WET"),
    ("Etc/UTC", "Zulu"),
];

static ECMA402_SUPPORTED: &[&str] = &[
    "Africa/Abidjan",
    "Africa/Accra",
    "Africa/Addis_Ababa",
    "Africa/Algiers",
    "Africa/Asmera",
    "Africa/Bamako",
    "Africa/Bangui",
    "Africa/Banjul",
    "Africa/Bissau",
    "Africa/Blantyre",
    "Africa/Brazzaville",
    "Africa/Bujumbura",
    "Africa/Cairo",
    "Africa/Casablanca",
    "Africa/Ceuta",
    "Africa/Conakry",
    "Africa/Dakar",
    "Africa/Dar_es_Salaam",
    "Africa/Djibouti",
    "Africa/Douala",
    "Africa/El_Aaiun",
    "Africa/Freetown",
    "Africa/Gaborone",
    "Africa/Harare",
    "Africa/Johannesburg",
    "Africa/Juba",
    "Africa/Kampala",
    "Africa/Khartoum",
    "Africa/Kigali",
    "Africa/Kinshasa",
    "Africa/Lagos",
    "Africa/Libreville",
    "Africa/Lome",
    "Africa/Luanda",
    "Africa/Lubumbashi",
    "Africa/Lusaka",
    "Africa/Malabo",
    "Africa/Maputo",
    "Africa/Maseru",
    "Africa/Mbabane",
    "Africa/Mogadishu",
    "Africa/Monrovia",
    "Africa/Nairobi",
    "Africa/Ndjamena",
    "Africa/Niamey",
    "Africa/Nouakchott",
    "Africa/Ouagadougou",
    "Africa/Porto-Novo",
    "Africa/Sao_Tome",
    "Africa/Tripoli",
    "Africa/Tunis",
    "Africa/Windhoek",
    "America/Adak",
    "America/Anchorage",
    "America/Anguilla",
    "America/Antigua",
    "America/Araguaina",
    "America/Argentina/La_Rioja",
    "America/Argentina/Rio_Gallegos",
    "America/Argentina/Salta",
    "America/Argentina/San_Juan",
    "America/Argentina/San_Luis",
    "America/Argentina/Tucuman",
    "America/Argentina/Ushuaia",
    "America/Aruba",
    "America/Asuncion",
    "America/Bahia",
    "America/Bahia_Banderas",
    "America/Barbados",
    "America/Belem",
    "America/Belize",
    "America/Blanc-Sablon",
    "America/Boa_Vista",
    "America/Bogota",
    "America/Boise",
    "America/Buenos_Aires",
    "America/Cambridge_Bay",
    "America/Campo_Grande",
    "America/Cancun",
    "America/Caracas",
    "America/Catamarca",
    "America/Cayenne",
    "America/Cayman",
    "America/Chicago",
    "America/Chihuahua",
    "America/Ciudad_Juarez",
    "America/Coral_Harbour",
    "America/Cordoba",
    "America/Costa_Rica",
    "America/Coyhaique",
    "America/Creston",
    "America/Cuiaba",
    "America/Curacao",
    "America/Danmarkshavn",
    "America/Dawson",
    "America/Dawson_Creek",
    "America/Denver",
    "America/Detroit",
    "America/Dominica",
    "America/Edmonton",
    "America/Eirunepe",
    "America/El_Salvador",
    "America/Fort_Nelson",
    "America/Fortaleza",
    "America/Glace_Bay",
    "America/Godthab",
    "America/Goose_Bay",
    "America/Grand_Turk",
    "America/Grenada",
    "America/Guadeloupe",
    "America/Guatemala",
    "America/Guayaquil",
    "America/Guyana",
    "America/Halifax",
    "America/Havana",
    "America/Hermosillo",
    "America/Indiana/Knox",
    "America/Indiana/Marengo",
    "America/Indiana/Petersburg",
    "America/Indiana/Tell_City",
    "America/Indiana/Vevay",
    "America/Indiana/Vincennes",
    "America/Indiana/Winamac",
    "America/Indianapolis",
    "America/Inuvik",
    "America/Iqaluit",
    "America/Jamaica",
    "America/Jujuy",
    "America/Juneau",
    "America/Kentucky/Monticello",
    "America/Kralendijk",
    "America/La_Paz",
    "America/Lima",
    "America/Los_Angeles",
    "America/Louisville",
    "America/Lower_Princes",
    "America/Maceio",
    "America/Managua",
    "America/Manaus",
    "America/Marigot",
    "America/Martinique",
    "America/Matamoros",
    "America/Mazatlan",
    "America/Mendoza",
    "America/Menominee",
    "America/Merida",
    "America/Metlakatla",
    "America/Mexico_City",
    "America/Miquelon",
    "America/Moncton",
    "America/Monterrey",
    "America/Montevideo",
    "America/Montserrat",
    "America/Nassau",
    "America/New_York",
    "America/Nome",
    "America/Noronha",
    "America/North_Dakota/Beulah",
    "America/North_Dakota/Center",
    "America/North_Dakota/New_Salem",
    "America/Ojinaga",
    "America/Panama",
    "America/Paramaribo",
    "America/Phoenix",
    "America/Port-au-Prince",
    "America/Port_of_Spain",
    "America/Porto_Velho",
    "America/Puerto_Rico",
    "America/Punta_Arenas",
    "America/Rankin_Inlet",
    "America/Recife",
    "America/Regina",
    "America/Resolute",
    "America/Rio_Branco",
    "America/Santarem",
    "America/Santiago",
    "America/Santo_Domingo",
    "America/Sao_Paulo",
    "America/Scoresbysund",
    "America/Sitka",
    "America/St_Barthelemy",
    "America/St_Johns",
    "America/St_Kitts",
    "America/St_Lucia",
    "America/St_Thomas",
    "America/St_Vincent",
    "America/Swift_Current",
    "America/Tegucigalpa",
    "America/Thule",
    "America/Tijuana",
    "America/Toronto",
    "America/Tortola",
    "America/Vancouver",
    "America/Whitehorse",
    "America/Winnipeg",
    "America/Yakutat",
    "Antarctica/Casey",
    "Antarctica/Davis",
    "Antarctica/DumontDUrville",
    "Antarctica/Macquarie",
    "Antarctica/Mawson",
    "Antarctica/McMurdo",
    "Antarctica/Palmer",
    "Antarctica/Rothera",
    "Antarctica/Syowa",
    "Antarctica/Troll",
    "Antarctica/Vostok",
    "Arctic/Longyearbyen",
    "Asia/Aden",
    "Asia/Almaty",
    "Asia/Amman",
    "Asia/Anadyr",
    "Asia/Aqtau",
    "Asia/Aqtobe",
    "Asia/Ashgabat",
    "Asia/Atyrau",
    "Asia/Baghdad",
    "Asia/Bahrain",
    "Asia/Baku",
    "Asia/Bangkok",
    "Asia/Barnaul",
    "Asia/Beirut",
    "Asia/Bishkek",
    "Asia/Brunei",
    "Asia/Calcutta",
    "Asia/Chita",
    "Asia/Colombo",
    "Asia/Damascus",
    "Asia/Dhaka",
    "Asia/Dili",
    "Asia/Dubai",
    "Asia/Dushanbe",
    "Asia/Famagusta",
    "Asia/Gaza",
    "Asia/Hebron",
    "Asia/Hong_Kong",
    "Asia/Hovd",
    "Asia/Irkutsk",
    "Asia/Jakarta",
    "Asia/Jayapura",
    "Asia/Jerusalem",
    "Asia/Kabul",
    "Asia/Kamchatka",
    "Asia/Karachi",
    "Asia/Katmandu",
    "Asia/Khandyga",
    "Asia/Krasnoyarsk",
    "Asia/Kuala_Lumpur",
    "Asia/Kuching",
    "Asia/Kuwait",
    "Asia/Macau",
    "Asia/Magadan",
    "Asia/Makassar",
    "Asia/Manila",
    "Asia/Muscat",
    "Asia/Nicosia",
    "Asia/Novokuznetsk",
    "Asia/Novosibirsk",
    "Asia/Omsk",
    "Asia/Oral",
    "Asia/Phnom_Penh",
    "Asia/Pontianak",
    "Asia/Pyongyang",
    "Asia/Qatar",
    "Asia/Qostanay",
    "Asia/Qyzylorda",
    "Asia/Rangoon",
    "Asia/Riyadh",
    "Asia/Saigon",
    "Asia/Sakhalin",
    "Asia/Samarkand",
    "Asia/Seoul",
    "Asia/Shanghai",
    "Asia/Singapore",
    "Asia/Srednekolymsk",
    "Asia/Taipei",
    "Asia/Tashkent",
    "Asia/Tbilisi",
    "Asia/Tehran",
    "Asia/Thimphu",
    "Asia/Tokyo",
    "Asia/Tomsk",
    "Asia/Ulaanbaatar",
    "Asia/Urumqi",
    "Asia/Ust-Nera",
    "Asia/Vientiane",
    "Asia/Vladivostok",
    "Asia/Yakutsk",
    "Asia/Yekaterinburg",
    "Asia/Yerevan",
    "Atlantic/Azores",
    "Atlantic/Bermuda",
    "Atlantic/Canary",
    "Atlantic/Cape_Verde",
    "Atlantic/Faeroe",
    "Atlantic/Madeira",
    "Atlantic/Reykjavik",
    "Atlantic/South_Georgia",
    "Atlantic/St_Helena",
    "Atlantic/Stanley",
    "Australia/Adelaide",
    "Australia/Brisbane",
    "Australia/Broken_Hill",
    "Australia/Darwin",
    "Australia/Eucla",
    "Australia/Hobart",
    "Australia/Lindeman",
    "Australia/Lord_Howe",
    "Australia/Melbourne",
    "Australia/Perth",
    "Australia/Sydney",
    "Etc/GMT+1",
    "Etc/GMT+10",
    "Etc/GMT+11",
    "Etc/GMT+12",
    "Etc/GMT+2",
    "Etc/GMT+3",
    "Etc/GMT+4",
    "Etc/GMT+5",
    "Etc/GMT+6",
    "Etc/GMT+7",
    "Etc/GMT+8",
    "Etc/GMT+9",
    "Etc/GMT-1",
    "Etc/GMT-10",
    "Etc/GMT-11",
    "Etc/GMT-12",
    "Etc/GMT-13",
    "Etc/GMT-14",
    "Etc/GMT-2",
    "Etc/GMT-3",
    "Etc/GMT-4",
    "Etc/GMT-5",
    "Etc/GMT-6",
    "Etc/GMT-7",
    "Etc/GMT-8",
    "Etc/GMT-9",
    "Europe/Amsterdam",
    "Europe/Andorra",
    "Europe/Astrakhan",
    "Europe/Athens",
    "Europe/Belgrade",
    "Europe/Berlin",
    "Europe/Bratislava",
    "Europe/Brussels",
    "Europe/Bucharest",
    "Europe/Budapest",
    "Europe/Busingen",
    "Europe/Chisinau",
    "Europe/Copenhagen",
    "Europe/Dublin",
    "Europe/Gibraltar",
    "Europe/Guernsey",
    "Europe/Helsinki",
    "Europe/Isle_of_Man",
    "Europe/Istanbul",
    "Europe/Jersey",
    "Europe/Kaliningrad",
    "Europe/Kiev",
    "Europe/Kirov",
    "Europe/Lisbon",
    "Europe/Ljubljana",
    "Europe/London",
    "Europe/Luxembourg",
    "Europe/Madrid",
    "Europe/Malta",
    "Europe/Mariehamn",
    "Europe/Minsk",
    "Europe/Monaco",
    "Europe/Moscow",
    "Europe/Oslo",
    "Europe/Paris",
    "Europe/Podgorica",
    "Europe/Prague",
    "Europe/Riga",
    "Europe/Rome",
    "Europe/Samara",
    "Europe/San_Marino",
    "Europe/Sarajevo",
    "Europe/Saratov",
    "Europe/Simferopol",
    "Europe/Skopje",
    "Europe/Sofia",
    "Europe/Stockholm",
    "Europe/Tallinn",
    "Europe/Tirane",
    "Europe/Ulyanovsk",
    "Europe/Vaduz",
    "Europe/Vatican",
    "Europe/Vienna",
    "Europe/Vilnius",
    "Europe/Volgograd",
    "Europe/Warsaw",
    "Europe/Zagreb",
    "Europe/Zurich",
    "Indian/Antananarivo",
    "Indian/Chagos",
    "Indian/Christmas",
    "Indian/Cocos",
    "Indian/Comoro",
    "Indian/Kerguelen",
    "Indian/Mahe",
    "Indian/Maldives",
    "Indian/Mauritius",
    "Indian/Mayotte",
    "Indian/Reunion",
    "Pacific/Apia",
    "Pacific/Auckland",
    "Pacific/Bougainville",
    "Pacific/Chatham",
    "Pacific/Easter",
    "Pacific/Efate",
    "Pacific/Enderbury",
    "Pacific/Fakaofo",
    "Pacific/Fiji",
    "Pacific/Funafuti",
    "Pacific/Galapagos",
    "Pacific/Gambier",
    "Pacific/Guadalcanal",
    "Pacific/Guam",
    "Pacific/Honolulu",
    "Pacific/Kiritimati",
    "Pacific/Kosrae",
    "Pacific/Kwajalein",
    "Pacific/Majuro",
    "Pacific/Marquesas",
    "Pacific/Midway",
    "Pacific/Nauru",
    "Pacific/Niue",
    "Pacific/Norfolk",
    "Pacific/Noumea",
    "Pacific/Pago_Pago",
    "Pacific/Palau",
    "Pacific/Pitcairn",
    "Pacific/Ponape",
    "Pacific/Port_Moresby",
    "Pacific/Rarotonga",
    "Pacific/Saipan",
    "Pacific/Tahiti",
    "Pacific/Tarawa",
    "Pacific/Tongatapu",
    "Pacific/Truk",
    "Pacific/Wake",
    "Pacific/Wallis",
    "UTC",
];

pub(crate) fn contains(value: &str) -> bool {
    ZONE1970_PRIMARY.binary_search(&value).is_ok()
        || BACKWARD_LINKS
            .binary_search_by(|(_, link)| link.cmp(&value))
            .is_ok()
}

pub(crate) fn ecma402_supported() -> &'static [&'static str] {
    ECMA402_SUPPORTED
}

pub(crate) fn link_duals(zone: &str) -> Vec<&'static str> {
    let mut out = Vec::new();
    for (primary, link) in BACKWARD_LINKS {
        if primary.eq_ignore_ascii_case(zone) {
            out.push(*link);
        } else if link.eq_ignore_ascii_case(zone) {
            out.push(*primary);
        }
    }
    out
}
