
static CURRENCY_REGULAR: &[&str] = &[
    "AED", "AFN", "ALL", "AMD", "AOA", "ARS", "AUD", "AWG", "AZN", "BAM", "BBD", "BDT", "BHD",
    "BIF", "BMD", "BND", "BOB", "BRL", "BSD", "BTN", "BWP", "BYN", "BZD", "CAD", "CDF", "CHF",
    "CLP", "CNY", "COP", "CRC", "CUP", "CVE", "CZK", "DJF", "DKK", "DOP", "DZD", "EGP", "ERN",
    "ETB", "EUR", "FJD", "FKP", "GBP", "GEL", "GHS", "GIP", "GMD", "GNF", "GTQ", "GYD", "HKD",
    "HNL", "HTG", "HUF", "IDR", "ILS", "INR", "IQD", "IRR", "ISK", "JMD", "JOD", "JPY", "KES",
    "KGS", "KHR", "KMF", "KPW", "KRW", "KWD", "KYD", "KZT", "LAK", "LBP", "LKR", "LRD", "LSL",
    "LYD", "MAD", "MDL", "MGA", "MKD", "MMK", "MNT", "MOP", "MRU", "MUR", "MVR", "MWK", "MXN",
    "MYR", "MZN", "NAD", "NGN", "NIO", "NOK", "NPR", "NZD", "OMR", "PAB", "PEN", "PGK", "PHP",
    "PKR", "PLN", "PYG", "QAR", "RON", "RSD", "RUB", "RWF", "SAR", "SBD", "SCR", "SDG", "SEK",
    "SGD", "SHP", "SLE", "SOS", "SRD", "SSP", "STN", "SYP", "SZL", "THB", "TJS", "TMT", "TND",
    "TOP", "TRY", "TTD", "TWD", "TZS", "UAH", "UGX", "USD", "UYU", "UZS", "VES", "VND", "VUV",
    "WST", "XAF", "XCD", "XCG", "XOF", "XPF", "YER", "ZAR", "ZMW", "ZWG",
];

static CURRENCY_DEPRECATED: &[&str] = &[
    "ADP", "AFA", "ALK", "ANG", "AOK", "AON", "AOR", "ARA", "ARL", "ARM", "ARP", "ATS", "AZM",
    "BAD", "BAN", "BEC", "BEF", "BEL", "BGL", "BGM", "BGN", "BGO", "BOL", "BOP", "BOV", "BRB",
    "BRC", "BRE", "BRN", "BRR", "BRZ", "BUK", "BYB", "BYR", "CHE", "CHW", "CLE", "CLF", "CNH",
    "CNX", "COU", "CSD", "CSK", "CUC", "CYP", "DDM", "DEM", "ECS", "ECV", "EEK", "ESA", "ESB",
    "ESP", "FIM", "FRF", "GEK", "GHC", "GNS", "GQE", "GRD", "GWE", "GWP", "HRD", "HRK", "IEP",
    "ILP", "ILR", "ISJ", "ITL", "KRH", "KRO", "LTL", "LTT", "LUC", "LUF", "LUL", "LVL", "LVR",
    "MAF", "MCF", "MDC", "MGF", "MKN", "MLF", "MRO", "MTL", "MTP", "MVP", "MXP", "MXV", "MZE",
    "MZM", "NIC", "NLG", "PEI", "PES", "PLZ", "PTE", "RHD", "ROL", "RUR", "SDD", "SDP", "SIT",
    "SKK", "SLL", "SRG", "STD", "SUR", "SVC", "TJR", "TMM", "TPE", "TRL", "UAK", "UGS", "USN",
    "USS", "UYI", "UYP", "UYW", "VEB", "VED", "VEF", "VNN", "XAD", "XAG", "XAU", "XBA", "XBB",
    "XBC", "XBD", "XDR", "XEU", "XFO", "XFU", "XPD", "XPT", "XRE", "XSU", "XTS", "XUA", "YDD",
    "YUD", "YUM", "YUN", "YUR", "ZAL", "ZMK", "ZRN", "ZRZ", "ZWD", "ZWL", "ZWR",
];

static CURRENCY_UNKNOWN: &[&str] = &["XXX"];

static CURRENCY_ECMA402_SUPPORTED: &[&str] = &[
    "ADP", "AED", "AFA", "AFN", "ALK", "ALL", "AMD", "ANG", "AOA", "AOK", "AON", "AOR", "ARA",
    "ARL", "ARM", "ARP", "ARS", "ATS", "AUD", "AWG", "AZM", "AZN", "BAD", "BAM", "BAN", "BBD",
    "BDT", "BEC", "BEF", "BEL", "BGL", "BGM", "BGN", "BGO", "BHD", "BIF", "BMD", "BND", "BOB",
    "BOL", "BOP", "BOV", "BRB", "BRC", "BRE", "BRL", "BRN", "BRR", "BRZ", "BSD", "BTN", "BUK",
    "BWP", "BYB", "BYN", "BYR", "BZD", "CAD", "CDF", "CHE", "CHF", "CHW", "CLE", "CLF", "CLP",
    "CNH", "CNX", "CNY", "COP", "COU", "CRC", "CSD", "CSK", "CUC", "CUP", "CVE", "CYP", "CZK",
    "DDM", "DEM", "DJF", "DKK", "DOP", "DZD", "ECS", "ECV", "EEK", "EGP", "ERN", "ESA", "ESB",
    "ESP", "ETB", "EUR", "FIM", "FJD", "FKP", "FRF", "GBP", "GEK", "GEL", "GHC", "GHS", "GIP",
    "GMD", "GNF", "GNS", "GQE", "GRD", "GTQ", "GWE", "GWP", "GYD", "HKD", "HNL", "HRD", "HRK",
    "HTG", "HUF", "IDR", "IEP", "ILP", "ILR", "ILS", "INR", "IQD", "IRR", "ISJ", "ISK", "ITL",
    "JMD", "JOD", "JPY", "KES", "KGS", "KHR", "KMF", "KPW", "KRH", "KRO", "KRW", "KWD", "KYD",
    "KZT", "LAK", "LBP", "LKR", "LRD", "LSL", "LTL", "LTT", "LUC", "LUF", "LUL", "LVL", "LVR",
    "LYD", "MAD", "MAF", "MCF", "MDC", "MDL", "MGA", "MGF", "MKD", "MKN", "MLF", "MMK", "MNT",
    "MOP", "MRO", "MRU", "MTL", "MTP", "MUR", "MVP", "MVR", "MWK", "MXN", "MXP", "MXV", "MYR",
    "MZE", "MZM", "MZN", "NAD", "NGN", "NIC", "NIO", "NLG", "NOK", "NPR", "NZD", "OMR", "PAB",
    "PEI", "PEN", "PES", "PGK", "PHP", "PKR", "PLN", "PLZ", "PTE", "PYG", "QAR", "RHD", "ROL",
    "RON", "RSD", "RUB", "RUR", "RWF", "SAR", "SBD", "SCR", "SDD", "SDG", "SDP", "SEK", "SGD",
    "SHP", "SIT", "SKK", "SLE", "SLL", "SOS", "SRD", "SRG", "SSP", "STD", "STN", "SUR", "SVC",
    "SYP", "SZL", "THB", "TJR", "TJS", "TMM", "TMT", "TND", "TOP", "TPE", "TRL", "TRY", "TTD",
    "TWD", "TZS", "UAH", "UAK", "UGS", "UGX", "USD", "USN", "USS", "UYI", "UYP", "UYU", "UYW",
    "UZS", "VEB", "VED", "VEF", "VES", "VND", "VNN", "VUV", "WST", "XAF", "XAG", "XAU", "XBA",
    "XBB", "XBC", "XBD", "XCD", "XCG", "XDR", "XEU", "XFO", "XFU", "XOF", "XPD", "XPF", "XPT",
    "XRE", "XSU", "XTS", "XUA", "XXX", "YDD", "YER", "YUD", "YUM", "YUN", "YUR", "ZAL", "ZAR",
    "ZMK", "ZMW", "ZRN", "ZRZ", "ZWD", "ZWG", "ZWL", "ZWR",
];

static CALENDAR_BCP47: &[&str] = &[
    "buddhist",
    "chinese",
    "coptic",
    "dangi",
    "ethioaa",
    "ethiopic",
    "gregory",
    "hebrew",
    "indian",
    "islamic",
    "islamic-civil",
    "islamic-rgsa",
    "islamic-tbla",
    "islamic-umalqura",
    "iso8601",
    "japanese",
    "orthodox",
    "persian",
    "roc",
];

static COLLATION_BCP47: &[&str] = &[
    "emoji", "eor", "phonebk", "pinyin", "searchjl", "stroke", "trad", "unihan", "zhuyin",
];

static NUMBERING_SYSTEM_NUMERIC: &[&str] = &[
    "adlm", "ahom", "arab", "arabext", "bali", "beng", "bhks", "brah", "cakm", "cham", "deva",
    "diak", "fullwide", "gara", "gong", "gonm", "gujr", "gukh", "guru", "hanidec", "hmng", "hmnp",
    "java", "kali", "kawi", "khmr", "knda", "krai", "lana", "lanatham", "laoo", "latn", "lepc",
    "limb", "mathbold", "mathdbl", "mathmono", "mathsanb", "mathsans", "mlym", "modi", "mong",
    "mroo", "mtei", "mymr", "mymrepka", "mymrpao", "mymrshan", "mymrtlng", "nagm", "newa", "nkoo",
    "olck", "onao", "orya", "osma", "outlined", "rohg", "saur", "segment", "shrd", "sind", "sinh",
    "sora", "sund", "sunu", "takr", "talu", "tamldec", "telu", "thai", "tibt", "tirh", "tnsa",
    "tols", "vaii", "wara", "wcho",
];

static UNIT_REGULAR: &[&str] = &[
    "acre",
    "acre-foot",
    "ampere",
    "arc-minute",
    "arc-second",
    "astronomical-unit",
    "atmosphere",
    "bar",
    "barrel",
    "beaufort",
    "becquerel",
    "bit",
    "british-thermal-unit",
    "british-thermal-unit-it",
    "bu-jp",
    "bushel",
    "byte",
    "calorie",
    "calorie-it",
    "candela",
    "carat",
    "celsius",
    "centiliter",
    "centimeter",
    "century",
    "chain",
    "cho",
    "coulomb",
    "cubic-centimeter",
    "cubic-foot",
    "cubic-inch",
    "cubic-kilometer",
    "cubic-meter",
    "cubic-mile",
    "cubic-yard",
    "cup",
    "cup-imperial",
    "cup-jp",
    "cup-metric",
    "dalton",
    "day",
    "day-person",
    "decade",
    "deciliter",
    "decimeter",
    "degree",
    "dessert-spoon",
    "dessert-spoon-imperial",
    "dot",
    "dot-per-centimeter",
    "dot-per-inch",
    "dram",
    "drop",
    "dunam",
    "earth-mass",
    "earth-radius",
    "electronvolt",
    "em",
    "fahrenheit",
    "farad",
    "fathom",
    "fluid-ounce",
    "fluid-ounce-imperial",
    "fluid-ounce-metric",
    "foodcalorie",
    "foot",
    "fortnight",
    "fun",
    "furlong",
    "g-force",
    "gallon",
    "gallon-imperial",
    "gasoline-energy-density",
    "generic",
    "gigabit",
    "gigabyte",
    "gigahertz",
    "gigawatt",
    "grain",
    "gram",
    "gray",
    "hectare",
    "hectoliter",
    "hectopascal",
    "henry",
    "hertz",
    "horsepower",
    "hour",
    "inch",
    "inch-ofhg",
    "item",
    "jigger",
    "jo-jp",
    "joule",
    "karat",
    "katal",
    "kelvin",
    "ken",
    "kilobit",
    "kilobyte",
    "kilocalorie",
    "kilogram",
    "kilogram-force",
    "kilohertz",
    "kilojoule",
    "kilometer",
    "kilometer-per-hour",
    "kilopascal",
    "kilowatt",
    "kilowatt-hour",
    "kilowatt-hour-per-100-kilometer",
    "knot",
    "koku",
    "kosaji",
    "light-speed",
    "light-year",
    "liter",
    "liter-per-100-kilometer",
    "liter-per-kilometer",
    "lumen",
    "lux",
    "megabit",
    "megabyte",
    "megahertz",
    "megaliter",
    "megapascal",
    "megapixel",
    "megawatt",
    "meter",
    "meter-per-second",
    "meter-per-square-second",
    "microgram",
    "micrometer",
    "microsecond",
    "mile",
    "mile-per-gallon",
    "mile-per-gallon-imperial",
    "mile-per-hour",
    "mile-scandinavian",
    "milliampere",
    "millibar",
    "milligram",
    "milligram-ofglucose-per-deciliter",
    "milliliter",
    "millimeter",
    "millimeter-ofhg",
    "millimole-per-liter",
    "millisecond",
    "milliwatt",
    "minute",
    "mole",
    "month",
    "month-person",
    "nanometer",
    "nanosecond",
    "nautical-mile",
    "newton",
    "newton-meter",
    "night",
    "ofglucose",
    "ofhg",
    "ohm",
    "osaji",
    "ounce",
    "ounce-troy",
    "parsec",
    "part",
    "part-per-1e6",
    "part-per-1e9",
    "pascal",
    "percent",
    "permille",
    "permyriad",
    "petabyte",
    "picometer",
    "pinch",
    "pint",
    "pint-imperial",
    "pint-metric",
    "pixel",
    "pixel-per-centimeter",
    "pixel-per-inch",
    "point",
    "pound",
    "pound-force",
    "pound-force-foot",
    "pound-force-per-square-inch",
    "quart",
    "quart-imperial",
    "quarter",
    "radian",
    "rankine",
    "revolution",
    "ri-jp",
    "rin",
    "rod",
    "sai",
    "se-jp",
    "second",
    "shaku",
    "shaku-cloth",
    "shaku-length",
    "siemens",
    "sievert",
    "slug",
    "solar-luminosity",
    "solar-mass",
    "solar-radius",
    "square-centimeter",
    "square-foot",
    "square-inch",
    "square-kilometer",
    "square-meter",
    "square-mile",
    "square-yard",
    "steradian",
    "stone",
    "sun",
    "tablespoon",
    "teaspoon",
    "terabit",
    "terabyte",
    "tesla",
    "therm-us",
    "to-jp",
    "ton",
    "tonne",
    "volt",
    "watt",
    "weber",
    "week",
    "week-person",
    "yard",
    "year",
    "year-person",
];

pub(crate) fn contains(key: &str, value: &str) -> bool {
    match key {
        "calendar" => CALENDAR_BCP47.binary_search(&value).is_ok(),
        "collation" => COLLATION_BCP47.binary_search(&value).is_ok(),
        "currency" => {
            CURRENCY_REGULAR.binary_search(&value).is_ok()
                || CURRENCY_DEPRECATED.binary_search(&value).is_ok()
                || CURRENCY_UNKNOWN.binary_search(&value).is_ok()
        }
        "numberingSystem" => NUMBERING_SYSTEM_NUMERIC.binary_search(&value).is_ok(),
        "unit" => UNIT_REGULAR.binary_search(&value).is_ok(),
        _ => false,
    }
}

pub(crate) fn currency_ecma402_supported() -> &'static [&'static str] {
    CURRENCY_ECMA402_SUPPORTED
}

pub(crate) fn collation_bcp47() -> &'static [&'static str] {
    COLLATION_BCP47
}
