
static CURRENCY_FRACTIONS: &[(&str, usize, usize, Option<usize>, Option<usize>)] = &[
    ("ADP", 0, 0, None, None),
    ("AFN", 0, 0, None, None),
    ("ALL", 0, 0, None, None),
    ("AMD", 2, 0, Some(0), Some(0)),
    ("BHD", 3, 0, None, None),
    ("BIF", 0, 0, None, None),
    ("BYN", 2, 0, None, None),
    ("BYR", 0, 0, None, None),
    ("CAD", 2, 0, None, Some(5)),
    ("CHF", 2, 0, None, Some(5)),
    ("CLF", 4, 0, None, None),
    ("CLP", 0, 0, None, None),
    ("COP", 0, 0, None, None),
    ("CRC", 2, 0, Some(0), Some(0)),
    ("CZK", 2, 0, Some(0), Some(0)),
    ("DEFAULT", 2, 0, None, None),
    ("DJF", 0, 0, None, None),
    ("DKK", 2, 0, None, Some(50)),
    ("ESP", 0, 0, None, None),
    ("GNF", 0, 0, None, None),
    ("GYD", 2, 0, Some(0), Some(0)),
    ("HUF", 0, 0, None, Some(5)),
    ("IDR", 0, 0, None, None),
    ("IQD", 0, 0, None, None),
    ("IRR", 0, 0, None, None),
    ("ISK", 0, 0, None, None),
    ("ITL", 0, 0, None, None),
    ("JOD", 3, 0, None, None),
    ("JPY", 0, 0, None, None),
    ("KMF", 0, 0, None, None),
    ("KPW", 0, 0, None, None),
    ("KRW", 0, 0, None, None),
    ("KWD", 3, 0, None, None),
    ("LAK", 0, 0, None, None),
    ("LBP", 0, 0, None, None),
    ("LUF", 0, 0, None, None),
    ("LYD", 3, 0, None, None),
    ("MGA", 0, 0, None, None),
    ("MGF", 0, 0, None, None),
    ("MMK", 0, 0, None, None),
    ("MNT", 2, 0, Some(0), Some(0)),
    ("MRO", 0, 0, None, None),
    ("MUR", 2, 0, Some(0), Some(0)),
    ("NOK", 2, 0, Some(0), Some(0)),
    ("OMR", 3, 0, None, None),
    ("PKR", 0, 0, None, None),
    ("PYG", 0, 0, None, None),
    ("RSD", 2, 0, Some(0), Some(0)),
    ("RWF", 0, 0, None, None),
    ("SEK", 2, 0, Some(0), Some(0)),
    ("SLE", 2, 0, None, None),
    ("SLL", 0, 0, None, None),
    ("SOS", 0, 0, None, None),
    ("STD", 0, 0, None, None),
    ("SYP", 0, 0, None, None),
    ("TMM", 0, 0, None, None),
    ("TND", 3, 0, None, None),
    ("TRL", 0, 0, None, None),
    ("TWD", 2, 0, Some(0), Some(0)),
    ("TZS", 2, 0, Some(0), Some(0)),
    ("UGX", 0, 0, None, None),
    ("UYI", 0, 0, None, None),
    ("UYW", 4, 0, None, None),
    ("UZS", 2, 0, Some(0), Some(0)),
    ("VEF", 2, 0, Some(0), Some(0)),
    ("VND", 0, 0, None, None),
    ("VUV", 0, 0, None, None),
    ("XAD", 2, 0, None, None),
    ("XAF", 0, 0, None, None),
    ("XAU", 2, 0, None, None),
    ("XOF", 0, 0, None, None),
    ("XPF", 0, 0, None, None),
    ("YER", 0, 0, None, None),
    ("ZMK", 0, 0, None, None),
    ("ZWD", 0, 0, None, None),
];

pub(crate) fn fraction_digits(code: &str) -> usize {
    let upper = code.to_ascii_uppercase();
    CURRENCY_FRACTIONS
        .iter()
        .find(|row| row.0 == upper.as_str())
        .or_else(|| CURRENCY_FRACTIONS.iter().find(|row| row.0 == "DEFAULT"))
        .map(|row| row.1)
        .unwrap_or(2)
}
