[package]
license.workspace = true
publish.workspace = true
name = "rusty-sqlite"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
crizzle-core = { path = "../crizzle-core" }
sql-core = { path = "../sql-core" }

[dev-dependencies]
crizzle-core = { path = "../crizzle-core" }
