[package]
license.workspace = true
publish.workspace = true
name = "rusty-js-jit"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]

cranelift-codegen = "0.118"
cranelift-frontend = "0.118"
cranelift-jit = "0.118"
cranelift-module = "0.118"
cranelift-native = "0.118"

rusty-js-bytecode = { path = "../rusty-js-bytecode" }

rusty-js-shapes = { path = "../rusty-js-shapes" }

[dev-dependencies]
rusty-js-ast = { path = "../rusty-js-ast" }
